config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#find', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def find
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save!
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <%= form_with model: @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/find.html.erb
<div class="container d=flex py-5">

  <div class="card" style="width: 30vw;">
    <div class="card-header">
      <%= @task.title %>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <%= @task.details %>
      </blockquote>
    </div>
  </div>
  <br>
  <%= link_to('Back to tasks', tasks_path) %>
  <%= link_to('Edit Task', task_edit_path) %>
</div>

app/views/tasks/index.html.erb
<div class="container d=flex py-5">
  <h1>My Tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
      <% if task.completed %>
        <% check = 'checked' %>
      <% else %>
        <% check = ''%>
      <% end %>
      <li>
        <%= link_to task.title, task_path(task)%> <input class="form-check-input" type="checkbox"  <%= check %> >
        <%= link_to "Delete",
        task_path(task),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
      %>
      </li>
    <% end %>
  </ul>
  <%= link_to 'New Task', new_task_path %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <%= form_with model: @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.submit %>
  <% end %>
</div>